# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-06 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
