# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alamat',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
