# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200507_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
    ]
