# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200507_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('olahraga', 'olahraga'), ('kesehatan', 'kesehatan'), ('unknown', 'unknown')], default='unknown', max_length=100),
        ),
    ]
